### ISSUE TITLE
ManagedShowOnStart seems to be bugged?

### ISSUE THREAD

**Issue by ahctang** [MFlisar/changelog#13]
Pardon me if I have misunderstood how your code works, but debugging into the source I have found this:
When an app is first installed and there is no local storage/cache, your function shouldShowChangelogOnStart will always return null, because the lastChangeLog variable was never set in SharedPreferences.

As a result, shouldShow always returns false in buildAndShowDialog, so the dialog never ever gets shown for the first time if you turn on the automatic management. If you set the management setting to false once, force the dialog to show, and then update the app version, the code seems to work as intended.

Could you please take a look at this?

**Comment by MFlisar** [comment]
If the value has not been set yet, you'll get `-1` as `lastChangelogVersion`, check this:

https://github.com/MFlisar/changelog/blob/815d6a452dcfbdf842f96051c843914c0c004029/lib/src/main/java/com/michaelflisar/changelog/internal/ChangelogPreferenceUtil.java#L18-L21

And on first app start after a new install, a **change**log does not make sense imho, so this is the expected behaviour, check out the comment here:

https://github.com/MFlisar/changelog/blob/815d6a452dcfbdf842f96051c843914c0c004029/lib/src/main/java/com/michaelflisar/changelog/internal/ChangelogPreferenceUtil.java#L32-L35

**Comment by ahctang** [comment]
Ah ok! I understand the intent behind your design now.

Sorry, false alarm!

**Comment by MFlisar** [comment]
If you want to show it on first app start, just do following in your app:

    // must be BEFORE the first managed start, as this will change the -1 to current apps version
    if (ChangelogPreferenceUtil.getAlreadyShownChangelogVersion() == -1)
    {
        // show it without managed start => will only be true ONCE in an apps lifetime
    }
    // now show it with managed start => from here on it will only show if a version update is detected

**Comment by marbat87** [comment]
@MFlisar  The method getAlreadyShownChangelogVersion is private so we cannot call it from application

**Comment by MFlisar** [comment]
will male it public in the next release
